### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by ZiggyStardust11983** [Automaticism/Promptvision#3]
I was able to get it working with a test directory but my main image directory is returning this error. I believe that directory is ~70k images, is there some limit in how large the directory can be? 

File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 774, in get
    raise self._value
IndexError: list index out of range

That is the recurring exception, occurring at either line 888 - parsed_data[Model] = sampler_settings[6] or 889 - parsed_data[Eta] = sampler_settings[7]

Here is the full error output

PS C:\Users\user\Promptvision> python .\gallery.py --imagedir "C:\Users\user\stable-diffusion-webui\outputs\images"
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\user\Promptvision\gallery.py", line 888, in read_exif_data
    parsed_data['Model'] = sampler_settings[6].split(": ")[1]
IndexError: list index out of range
"""
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\Promptvision\gallery.py", line 1007, in <module>
    bulk_exif_data = mp_bulk_exif_read(filtered_images)
  File "C:\Users\user\Promptvision\gallery.py", line 933, in mp_bulk_exif_read
    row = result.get()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 774, in get
    raise self._value
IndexError: list index out of range

Thanks in advance and apologies if it's something I've done or missed.

**Comment by kamtschatka** [comment]
Same thing happens to me as well. I had a blank (" ") in the path and verified if that caused issues. It doesn't. I also tried it with a single file in a single folder directly in "D:\Lion" and I get the list index out of range issue as well.

Additionally the README.MD seems to be wrong, since it references "app.py", but the command below it shows "gallery.py"

**Comment by Automaticism** [comment]
Sorry, I broke the parsing of the exif data. I am working on it.

**Comment by Automaticism** [comment]
I made a test dataset with images that:
- Had no prompts
- Had only negative prompt
- Had only positive prompt
- Had both prompts
- Had extras

In my limited testing everything except for `Hashes: {"model": "7f16bbcd80"}` is being extracted properly. 
I'll fix that later. It should work now.

**Comment by kamtschatka** [comment]
I did a git pull and It loads now, but it does not show the data in the correct location:
![image](https://user-images.githubusercontent.com/22147234/227378112-ba051d43-6a10-4ff7-8fcf-e8e29c0ab2bb.png)

Here is my source file: 
![00108-1919503736](https://user-images.githubusercontent.com/22147234/227378539-ef71195c-6619-40b5-9482-c5ef214db2cf.png)


Additionally it doesn't seem to handle subfolders, that would be a cool improvement idea in the future.

**Comment by Automaticism** [comment]
Subfolders should be supported. It just shows them all as being in the same folder. If you look at "File" it should show which path you have.

Thanks for your preview!

![image](https://user-images.githubusercontent.com/20763070/227381793-d48ce193-a750-479e-bb56-fbb0836e60ec.png)

Latest commit fixes the lion example.
You didn't have "hashes" appended. Maybe it's if you're not using loras. It's a little while since I made the exif hashing logic. And it's so stupid since the keys are not properly set in automatic1111's sd gui.

**Comment by kamtschatka** [comment]
ok cool, had to delete the metadata folder and now it works(trailing "," could be removed to make it perfect).
Subdirectories actually also work, but I have so many images that It does not show all of them on the right side. 

Thanks a lot, great tool!

**Comment by Automaticism** [comment]
It only loads a subset at a time. If you scroll it should load some more. If you e.g. choose the last image in the thumbnail section it will load more. This is because loading 200+++ images as thumbnails will slow it down if you are quickly scrolling through images. Remember that hotkeys also work :)

**Comment by Automaticism** [comment]
Commas now removed as well!
