### ISSUE TITLE
Automatic1111 Extension & View Watermarking Data

### ISSUE THREAD

**Issue by DreamOfGit** [Automaticism/Promptvision#8]
**Describe the solution you'd like**

I'd love if this is a tab within A111. Running it as an additional application when it's really just a library of image + prompts feels a bit overheady.

Also one of the fields that would be nice to see is if the image has the embedded "Hidden" Stable Diffusion watermark.

eg.
https://medium.com/@steinsfu/stable-diffusion-the-invisible-watermark-in-generated-images-2d68e2ab1241
```
import cv2
from imwatermark import WatermarkDecoderdef testit(img_path):
    bgr = cv2.imread(img_path)
    decoder = WatermarkDecoder('bytes', 136)
    watermark = decoder.decode(bgr, 'dwtDct')
    try:
        dec = watermark.decode('utf-8')
    except:
        dec = "null"
    print(dec)
```

**Comment by Automaticism** [comment]
1. Yes, I agree. I'll have to check that when I have time to do so. 
2. That's a neat idea. I am thinking that is something which is nicely added by having to check for an argument such as --watermark True and then running that in the EXIF part of the code and just adding it to that dict.

**Comment by Automaticism** [comment]
Given that github.com/AlUlkesh/stable-diffusion-webui-images-browser exists I see no further point in making a sdwebui plugin. 

I'll be continuing on with this standalone image viewer. Soon I'll be extending this with dataframe browsing that will enable users extensive insight into their own prompts and such based on their own metadata additions. I haven't yet landed on which framework since there is quite the extensive list of frameworks to choose from (e.g. Dash, Streamlit, Panel, and so on).
